import type { Metadata } from 'next';
import { ClientProviders } from './providers';
import { ApolloWrapper } from '@/lib/apollo-wrapper';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <ClientProviders>{children}</ClientProviders>
        </ApolloWrapper>
      </body>
    </html>
  );
}
