'use client';

import { responsive, useTheme } from '@instacart/ids-core';
import { getDashboardBusinessPalette } from '@/app/dashboard/dashboard-business-theme';

export function useDashboardPromptComposerStyles() {
  const theme = useTheme();
  const businessPalette = getDashboardBusinessPalette(theme);

  return {
    modalStyles: {
      modal: {
        width: 'min(1200px, calc(100vw - 32px))',
        maxWidth: 'none',
        height: 'min(860px, calc(100vh - 32px))',
      },
    },
    contentLayout: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '20px',
      paddingTop: '8px',
    },
    modalMotionShell: {
      display: 'flex',
      flexDirection: 'column' as const,
      height: '100%',
      transformOrigin: '50% 18%',
      willChange: 'transform, opacity',
    },
    introBlock: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '8px',
      maxWidth: '46rem',
    },
    eyebrow: {
      letterSpacing: '0.08em',
      textTransform: 'uppercase' as const,
    },
    section: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '12px',
    },
    sectionHeader: {
      display: 'flex',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      gap: '12px',
      flexWrap: 'wrap' as const,
    },
    previewLayout: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '16px',
    },
    previewPromptPanel: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '8px',
      padding: '18px',
      borderRadius: theme.radius.r12,
      border: `1px solid ${businessPalette.blueberryBorder}`,
      background: businessPalette.canvasGradient,
    },
    previewWidgetCard: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '18px',
      padding: '20px',
      borderRadius: theme.radius.r12,
      border: `1px solid ${businessPalette.blueberryBorder}`,
      backgroundColor: theme.colors.systemGrayscale00,
      boxShadow: '0 14px 34px rgba(17, 24, 39, 0.08)',
    },
    previewWidgetHeader: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '14px',
      [responsive.up('r')]: {
        flexDirection: 'row' as const,
        alignItems: 'flex-start',
        justifyContent: 'space-between',
      },
    },
    previewWidgetHeaderCopy: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '6px',
      minWidth: 0,
      flex: 1,
    },
    previewWidgetMeta: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      flexWrap: 'wrap' as const,
      flexShrink: 0,
    },
    previewWidgetBadge: {
      display: 'inline-flex',
      alignItems: 'center',
      padding: '7px 10px',
      borderRadius: '999px',
      border: `1px solid ${businessPalette.blueberryBorder}`,
      backgroundColor: businessPalette.blueberrySoft,
    },
    previewWidgetBadgeAccent: {
      borderColor: businessPalette.elderberryBorder,
      backgroundColor: businessPalette.elderberrySoft,
    },
    previewWidgetCanvas: {
      minHeight: '320px',
      padding: '18px',
      borderRadius: theme.radius.r12,
      border: `1px solid ${businessPalette.blueberryBorder}`,
      background: 'linear-gradient(180deg, rgba(43, 120, 198, 0.04) 0%, rgba(255, 255, 255, 1) 100%)',
      overflow: 'hidden' as const,
    },
    widgetTypePanel: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '14px',
      padding: '18px',
      borderRadius: theme.radius.r12,
      border: `1px solid ${businessPalette.blueberryBorder}`,
      background: businessPalette.canvasGradient,
    },
    widgetCatalog: {
      display: 'grid',
      gap: '14px',
      gridTemplateColumns: 'repeat(1, minmax(0, 1fr))',
      [responsive.up('r')]: {
        gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      },
    },
    widgetOption: {
      appearance: 'none' as const,
      boxSizing: 'border-box' as const,
      display: 'flex',
      flexDirection: 'column' as const,
      alignItems: 'stretch',
      gap: '12px',
      width: '100%',
      minWidth: 0,
      minHeight: '188px',
      padding: '14px',
      borderRadius: theme.radius.r12,
      border: `1px solid ${businessPalette.blueberryBorder}`,
      backgroundColor: theme.colors.systemGrayscale00,
      textAlign: 'left' as const,
      cursor: 'pointer',
      overflow: 'visible' as const,
      font: 'inherit',
      transition: 'transform 0.2s ease, border-color 0.2s ease, box-shadow 0.2s ease, background-color 0.2s ease',
      '&:hover': {
        transform: 'translateY(-1px)',
        borderColor: businessPalette.blueberry,
        boxShadow: '0 12px 26px rgba(17, 24, 39, 0.06)',
      },
      '&:focus-visible': {
        outline: `2px solid ${businessPalette.blueberry}`,
        outlineOffset: '3px',
      },
    },
    widgetOptionSelected: {
      borderWidth: '2px',
      borderColor: businessPalette.elderberry,
      backgroundColor: 'rgba(255, 255, 255, 0.98)',
      boxShadow: '0 14px 28px rgba(110, 72, 229, 0.12)',
    },
    widgetOptionHeader: {
      display: 'flex',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: '12px',
      minWidth: 0,
    },
    widgetOptionText: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '4px',
      minWidth: 0,
      flex: 1,
    },
    widgetOptionStatus: {
      display: 'inline-flex',
      alignItems: 'center',
      padding: '6px 10px',
      borderRadius: '999px',
      border: `1px solid ${businessPalette.blueberryBorder}`,
      backgroundColor: businessPalette.blueberrySoft,
      flexShrink: 0,
    },
    widgetOptionStatusSelected: {
      borderColor: businessPalette.elderberryBorder,
      backgroundColor: businessPalette.elderberrySoft,
    },
    widgetPreviewSurface: {
      display: 'flex',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      height: '118px',
      flexShrink: 0,
      borderRadius: theme.radius.r12,
      border: `1px solid ${businessPalette.blueberryBorder}`,
      background: 'linear-gradient(180deg, rgba(43, 120, 198, 0.05) 0%, rgba(255, 255, 255, 0.96) 100%)',
      overflow: 'hidden' as const,
      padding: '12px',
    },
    previewMetric: {
      display: 'flex',
      flexDirection: 'column' as const,
      justifyContent: 'space-between',
      gap: '8px',
      width: '100%',
      height: '100%',
    },
    previewMetricTag: {
      display: 'inline-flex',
      alignItems: 'center',
      width: 'fit-content',
      padding: '6px 8px',
      borderRadius: '999px',
      backgroundColor: businessPalette.elderberrySoft,
      border: `1px solid ${businessPalette.elderberryBorder}`,
    },
    previewMetricFooter: {
      display: 'grid',
      gap: '6px',
      gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
      alignItems: 'end',
    },
    previewMetricBar: {
      borderRadius: '999px 999px 4px 4px',
      background: 'linear-gradient(180deg, rgba(110, 72, 229, 0.92) 0%, rgba(43, 120, 198, 0.76) 100%)',
    },
    previewChartSvg: {
      width: '100%',
      height: '100%',
      display: 'block',
    },
    previewBarChart: {
      display: 'flex',
      alignItems: 'flex-end',
      gap: '8px',
      width: '100%',
      height: '100%',
    },
    previewBarColumn: {
      flex: 1,
      borderRadius: '999px 999px 4px 4px',
      background: 'linear-gradient(180deg, rgba(110, 72, 229, 0.92) 0%, rgba(43, 120, 198, 0.76) 100%)',
    },
    previewDonutWrap: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '12px',
      width: '100%',
      height: '100%',
    },
    previewDonut: {
      width: '72px',
      height: '72px',
      borderRadius: '999px',
      background:
        'conic-gradient(#6E48E5 0deg 132deg, #2B78C6 132deg 262deg, rgba(43, 120, 198, 0.2) 262deg 360deg)',
      position: 'relative' as const,
      flexShrink: 0,
      '&::after': {
        content: '""',
        position: 'absolute' as const,
        inset: '16px',
        borderRadius: '999px',
        backgroundColor: theme.colors.systemGrayscale00,
      },
    },
    previewLegend: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '8px',
      flex: 1,
      minWidth: 0,
    },
    previewLegendRow: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
    },
    previewLegendDot: {
      width: '8px',
      height: '8px',
      borderRadius: '999px',
      flexShrink: 0,
    },
    previewLegendBar: {
      height: '8px',
      borderRadius: '999px',
      flex: 1,
      backgroundColor: businessPalette.blueberrySoft,
    },
    previewInsightList: {
      display: 'flex',
      flexDirection: 'column' as const,
      justifyContent: 'center',
      gap: '10px',
      width: '100%',
      height: '100%',
    },
    previewInsightRow: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
    },
    previewInsightDot: {
      width: '8px',
      height: '8px',
      borderRadius: '999px',
      backgroundColor: businessPalette.elderberry,
      flexShrink: 0,
    },
    previewInsightLine: {
      height: '9px',
      borderRadius: '999px',
      backgroundColor: businessPalette.blueberrySoft,
    },
    textarea: {
      width: '100%',
      minHeight: '148px',
      resize: 'vertical' as const,
      borderRadius: theme.radius.r12,
      border: `1px solid ${theme.colors.systemGrayscale20}`,
      padding: '16px 18px',
      font: 'inherit',
      color: theme.colors.systemGrayscale90,
      backgroundColor: theme.colors.systemGrayscale00,
      boxShadow: 'inset 0 1px 0 rgba(255, 255, 255, 0.9)',
      '&:focus': {
        outline: `2px solid ${businessPalette.blueberry}`,
        outlineOffset: '2px',
      },
      '&::placeholder': {
        color: theme.colors.systemGrayscale50,
      },
    },
    hintRow: {
      display: 'flex',
      flexWrap: 'wrap' as const,
      gap: '8px',
    },
    suggestionChip: {
      display: 'inline-flex',
      alignItems: 'center',
      padding: '10px 14px',
      borderRadius: '999px',
      border: `1px solid ${businessPalette.blueberryBorder}`,
      backgroundColor: businessPalette.blueberrySoft,
      cursor: 'pointer',
      transition: 'transform 0.2s ease, border-color 0.2s ease, background-color 0.2s ease',
      '&:hover': {
        transform: 'translateY(-1px)',
        borderColor: businessPalette.blueberry,
        backgroundColor: theme.colors.systemGrayscale00,
      },
    },
    helperText: {
      color: theme.colors.systemGrayscale60,
    },
    fieldLabel: {
      color: businessPalette.blueberryDark,
    },
    warningText: {
      color: '#B42318',
    },
    errorText: {
      color: '#B42318',
    },
    buttonRow: {
      display: 'grid',
      gap: '12px',
      width: '100%',
      gridTemplateColumns: 'minmax(0, 1fr)',
      [responsive.up('r')]: {
        gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
      },
    },
    buttonRowPreview: {
      [responsive.up('r')]: {
        gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      },
    },
    footerButtonBase: {
      appearance: 'none' as const,
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
      minHeight: '48px',
      padding: '0 18px',
      borderRadius: theme.radius.r12,
      border: `1px solid ${theme.colors.systemGrayscale20}`,
      backgroundColor: theme.colors.systemGrayscale00,
      color: theme.colors.systemGrayscale90,
      font: 'inherit',
      fontWeight: 600,
      cursor: 'pointer',
      transition: 'transform 0.18s ease, border-color 0.18s ease, background-color 0.18s ease, box-shadow 0.18s ease',
      '&:hover:not(:disabled)': {
        transform: 'translateY(-1px)',
        boxShadow: '0 12px 24px rgba(17, 24, 39, 0.08)',
      },
      '&:focus-visible': {
        outline: `2px solid ${businessPalette.blueberry}`,
        outlineOffset: '3px',
      },
      '&:disabled': {
        opacity: 0.58,
        cursor: 'not-allowed',
        boxShadow: 'none',
      },
    },
    footerPrimaryButton: {
      backgroundColor: businessPalette.elderberry,
      borderColor: businessPalette.elderberry,
      color: theme.colors.systemGrayscale00,
      '&:hover:not(:disabled)': {
        backgroundColor: businessPalette.elderberryDark,
        borderColor: businessPalette.elderberryDark,
      },
    },
    footerSecondaryButton: {
      borderColor: businessPalette.blueberryBorder,
      backgroundColor: businessPalette.blueberrySoft,
      color: businessPalette.blueberryDark,
      '&:hover:not(:disabled)': {
        borderColor: businessPalette.blueberry,
        backgroundColor: theme.colors.systemGrayscale00,
      },
    },
    footerNeutralButton: {
      '&:hover:not(:disabled)': {
        borderColor: theme.colors.systemGrayscale30,
      },
    },
  } as const;
}

export type DashboardPromptComposerStyles = ReturnType<typeof useDashboardPromptComposerStyles>;
