import type {
  InsightDimensionDefinition,
  InsightMetricDefinition,
  InsightQuestionDefinition,
} from '@/app/insights/insights-types';

export const insightCoverageAuditNotes = [
  'This workspace does not include a local `carrot/data/medusa` checkout, so the audit is based on internal Medusa documentation, business-domain code, and the IC Business hackathon notes.',
  'Questions marked `ready` are the starter Medusa-backed paths that are verified in this repo today and safe for end-to-end execution.',
  'Questions marked `needs_medusa_config` match recurring PM and sales asks, but still need upstream Medusa aliases, derived measures, or dimension wiring before they can run safely.',
  'Questions marked `blocked` require hybrid enrichment beyond the current Medusa-only path, such as CRM ownership, total location footprint, or non-Medusa product event logs.',
];

export const insightDimensionCatalog = {
  deliveredDate: {
    id: 'deliveredDate',
    label: 'Delivered date',
    description: 'Delivery completion date for business delivery metrics.',
    medusaName: 'dim_delivered_date_pt',
    kind: 'date',
    coverageStatus: 'ready',
  },
  vertical: {
    id: 'vertical',
    label: 'Vertical',
    description: 'Business delivery vertical used for breakdowns like grocery or restaurant.',
    medusaName: 'dim_vertical',
    kind: 'category',
    coverageStatus: 'ready',
  },
  signupDate: {
    id: 'signupDate',
    label: 'Signup date',
    description: 'Date when a business or prospective business account first signed up.',
    medusaName: null,
    kind: 'date',
    coverageStatus: 'needs_medusa_config',
  },
  activationDate: {
    id: 'activationDate',
    label: 'Activation date',
    description: 'Date when a signed-up business first became active.',
    medusaName: null,
    kind: 'date',
    coverageStatus: 'needs_medusa_config',
  },
  businessId: {
    id: 'businessId',
    label: 'Business account',
    description: 'Business account or organization identifier for account-level reporting.',
    medusaName: null,
    kind: 'category',
    coverageStatus: 'needs_medusa_config',
  },
  retailer: {
    id: 'retailer',
    label: 'Retailer',
    description: 'Retailer or partner dimension for business spend and order breakdowns.',
    medusaName: null,
    kind: 'category',
    coverageStatus: 'needs_medusa_config',
  },
  salesSegment: {
    id: 'salesSegment',
    label: 'Sales segment',
    description: 'Commercial segment grouping for sales readouts and follow-up.',
    medusaName: null,
    kind: 'category',
    coverageStatus: 'needs_medusa_config',
  },
  signupSource: {
    id: 'signupSource',
    label: 'Signup source',
    description: 'Signup source or acquisition surface for new business accounts.',
    medusaName: null,
    kind: 'category',
    coverageStatus: 'needs_medusa_config',
  },
  landingPage: {
    id: 'landingPage',
    label: 'Landing page',
    description: 'Landing page or campaign surface for partner-sourced acquisition reporting.',
    medusaName: null,
    kind: 'category',
    coverageStatus: 'needs_medusa_config',
  },
  invoiceSurface: {
    id: 'invoiceSurface',
    label: 'Invoice surface',
    description: 'Feature or callout surface used to drive invoicing adoption.',
    medusaName: null,
    kind: 'category',
    coverageStatus: 'needs_medusa_config',
  },
  partnerName: {
    id: 'partnerName',
    label: 'Partner',
    description: 'Distribution or acquisition partner driving business signups.',
    medusaName: null,
    kind: 'category',
    coverageStatus: 'needs_medusa_config',
  },
  accountOwner: {
    id: 'accountOwner',
    label: 'Account owner',
    description: 'Sales owner or book-of-business assignment for opportunity tracking.',
    medusaName: null,
    kind: 'category',
    coverageStatus: 'blocked',
  },
} satisfies Record<string, InsightDimensionDefinition>;

export const insightMetricCatalog = {
  businessDeliveries: {
    id: 'businessDeliveries',
    label: 'Business deliveries',
    description: 'Delivered order count for the business delivery segment.',
    medusaName: 'eco_business_deliveries',
    coverageStatus: 'ready',
    defaultDateDimensionId: 'deliveredDate',
    allowedDimensionIds: ['deliveredDate', 'vertical'],
  },
  businessSignups: {
    id: 'businessSignups',
    label: 'Business signups',
    description: 'New Instacart Business signups across acquisition sources.',
    medusaName: null,
    coverageStatus: 'needs_medusa_config',
    defaultDateDimensionId: 'signupDate',
    allowedDimensionIds: ['signupDate', 'signupSource', 'landingPage', 'partnerName'],
  },
  activatedBusinesses: {
    id: 'activatedBusinesses',
    label: 'Activated businesses',
    description: 'Business accounts that reached the first meaningful activation milestone.',
    medusaName: null,
    coverageStatus: 'needs_medusa_config',
    defaultDateDimensionId: 'activationDate',
    allowedDimensionIds: ['activationDate', 'signupSource', 'salesSegment'],
  },
  personalToBusinessUpgrades: {
    id: 'personalToBusinessUpgrades',
    label: 'Personal to business upgrades',
    description: 'Personal shoppers or leads that converted into business accounts.',
    medusaName: null,
    coverageStatus: 'needs_medusa_config',
    defaultDateDimensionId: 'activationDate',
    allowedDimensionIds: ['activationDate', 'signupSource', 'landingPage'],
  },
  icbGtv: {
    id: 'icbGtv',
    label: 'ICB GTV',
    description: 'Gross transaction value for Instacart Business marketplace activity.',
    medusaName: null,
    coverageStatus: 'needs_medusa_config',
    defaultDateDimensionId: 'deliveredDate',
    allowedDimensionIds: ['deliveredDate', 'retailer', 'salesSegment', 'businessId'],
  },
  icbOrders: {
    id: 'icbOrders',
    label: 'ICB orders',
    description: 'Order count for Instacart Business marketplace activity.',
    medusaName: null,
    coverageStatus: 'needs_medusa_config',
    defaultDateDimensionId: 'deliveredDate',
    allowedDimensionIds: ['deliveredDate', 'retailer', 'salesSegment', 'businessId'],
  },
  icbAvgOrderValue: {
    id: 'icbAvgOrderValue',
    label: 'ICB average order value',
    description: 'Average order value for Instacart Business orders.',
    medusaName: null,
    coverageStatus: 'needs_medusa_config',
    defaultDateDimensionId: 'deliveredDate',
    allowedDimensionIds: ['deliveredDate', 'retailer', 'salesSegment'],
  },
  invoiceAdoption: {
    id: 'invoiceAdoption',
    label: 'Invoice adoption',
    description: 'Adoption rate of invoice-related features across business accounts.',
    medusaName: null,
    coverageStatus: 'needs_medusa_config',
    defaultDateDimensionId: 'activationDate',
    allowedDimensionIds: ['activationDate', 'invoiceSurface', 'salesSegment'],
  },
  invoicingCalloutLift: {
    id: 'invoicingCalloutLift',
    label: 'Invoicing callout lift',
    description: 'Relative lift from invoicing feature callouts or growth surfaces.',
    medusaName: null,
    coverageStatus: 'needs_medusa_config',
    defaultDateDimensionId: 'activationDate',
    allowedDimensionIds: ['activationDate', 'invoiceSurface'],
  },
  partnerAttributedBusinesses: {
    id: 'partnerAttributedBusinesses',
    label: 'Partner-attributed businesses',
    description: 'Businesses attributed to a partner, landing page, or co-marketing surface.',
    medusaName: null,
    coverageStatus: 'needs_medusa_config',
    defaultDateDimensionId: 'signupDate',
    allowedDimensionIds: ['signupDate', 'partnerName', 'landingPage'],
  },
  landingPageConversion: {
    id: 'landingPageConversion',
    label: 'Landing page conversion',
    description: 'Conversion performance for partner and campaign landing pages.',
    medusaName: null,
    coverageStatus: 'needs_medusa_config',
    defaultDateDimensionId: 'signupDate',
    allowedDimensionIds: ['signupDate', 'landingPage', 'partnerName'],
  },
  icbSpendDropRisk: {
    id: 'icbSpendDropRisk',
    label: 'Spend drop risk',
    description: 'Large accounts with material GTV decline compared with prior periods.',
    medusaName: null,
    coverageStatus: 'needs_medusa_config',
    defaultDateDimensionId: 'deliveredDate',
    allowedDimensionIds: ['businessId', 'salesSegment', 'accountOwner'],
  },
  icbLocationPenetration: {
    id: 'icbLocationPenetration',
    label: 'Location penetration',
    description: 'Observed business ordering locations versus estimated total footprint.',
    medusaName: null,
    coverageStatus: 'blocked',
    defaultDateDimensionId: null,
    allowedDimensionIds: ['businessId', 'accountOwner'],
  },
} satisfies Record<string, InsightMetricDefinition>;

export const insightQuestionCatalog = [
  {
    id: 'business-deliveries-last-30-days',
    category: 'business_health',
    persona: 'leadership',
    title: 'Business deliveries snapshot',
    prompt: 'How many business deliveries happened in the last 30 days?',
    description: 'Top-line snapshot for the currently verified Medusa-backed business delivery metric.',
    aliases: ['monthly delivery snapshot', 'business delivery count', 'last 30 days deliveries'],
    improvementFocus: 'health',
    preferredWidgetType: 'metric',
    coverageStatus: 'ready',
    metricIds: ['businessDeliveries'],
    dimensionId: null,
    timeBucket: 'none',
    relativeRange: 'past_30_days',
    answerShape: 'metric',
    filters: [],
    coverageNotes: [
      'This is the smallest production-backed question in the current catalog and is used as the default verified Medusa read.',
    ],
  },
  {
    id: 'weekly-business-deliveries-trend',
    category: 'business_health',
    persona: 'leadership',
    title: 'Weekly business deliveries trend',
    prompt: 'How many business deliveries are we doing each week over the last 12 weeks?',
    description: 'Trendline for the one business metric currently verified in Medusa from accessible internal docs.',
    aliases: ['weekly delivery trend', 'delivery pace', 'business deliveries over time'],
    improvementFocus: 'health',
    preferredWidgetType: 'lineChart',
    coverageStatus: 'ready',
    metricIds: ['businessDeliveries'],
    dimensionId: 'deliveredDate',
    timeBucket: 'week',
    relativeRange: 'past_12_weeks',
    answerShape: 'lineChart',
    filters: [],
    coverageNotes: [
      'Backed by `eco_business_deliveries` from the Growth delivery segment metric group.',
      'Uses the documented `dim_delivered_date_pt` time dimension.',
    ],
  },
  {
    id: 'business-deliveries-by-vertical',
    category: 'segment_breakdown',
    persona: 'pm',
    title: 'Business deliveries by vertical',
    prompt: 'Which verticals drove the most business deliveries in the last 30 days?',
    description: 'Vertical-level breakdown for a recent business delivery readout.',
    aliases: ['vertical mix', 'business delivery verticals', 'top verticals by deliveries'],
    improvementFocus: 'segmentation',
    preferredWidgetType: 'barChart',
    coverageStatus: 'ready',
    metricIds: ['businessDeliveries'],
    dimensionId: 'vertical',
    timeBucket: 'none',
    relativeRange: 'past_30_days',
    answerShape: 'barChart',
    filters: [],
    coverageNotes: [
      'Backed by `eco_business_deliveries` with the documented `dim_vertical` dimension.',
      'Good starter question for validating that the Medusa SQL server is reachable end-to-end.',
    ],
  },
  {
    id: 'signup-source-performance',
    category: 'acquisition',
    persona: 'pm',
    title: 'Business signups by source',
    prompt: 'Which signup sources drove the most new business signups in the last 30 days?',
    description: 'Acquisition readout for PMs trying to understand which sources are driving top-of-funnel business demand.',
    aliases: ['acquisition source performance', 'signup channel mix', 'business signups by source'],
    improvementFocus: 'acquisition',
    preferredWidgetType: 'barChart',
    coverageStatus: 'needs_medusa_config',
    metricIds: ['businessSignups'],
    dimensionId: 'signupSource',
    timeBucket: 'none',
    relativeRange: 'past_30_days',
    answerShape: 'barChart',
    filters: [],
    coverageNotes: [
      'Needs a verified signup-source dimension and new-business signup metric in Medusa before it can be executed safely.',
    ],
  },
  {
    id: 'signup-to-activation-trend',
    category: 'activation',
    persona: 'pm',
    title: 'Signup to activation trend',
    prompt: 'How many businesses are activating each week, and is activation improving over time?',
    description: 'Activation trend question for PMs monitoring whether new signups are getting to first value quickly enough.',
    aliases: ['activation trend', 'weekly activations', 'new business activation pace'],
    improvementFocus: 'activation',
    preferredWidgetType: 'lineChart',
    coverageStatus: 'needs_medusa_config',
    metricIds: ['activatedBusinesses'],
    dimensionId: 'activationDate',
    timeBucket: 'week',
    relativeRange: 'past_12_weeks',
    answerShape: 'lineChart',
    filters: [],
    coverageNotes: [
      'Requires a stable activation-event metric plus an approved activation date dimension in the IC Business Medusa model.',
    ],
  },
  {
    id: 'personal-to-business-upgrade-performance',
    category: 'activation',
    persona: 'pm',
    title: 'Personal to business upgrade performance',
    prompt: 'Which signup surfaces are converting personal shoppers into business accounts most effectively?',
    description: 'Improvement-oriented question for the hackathon dashboard where PMs want to compare which entry points drive business upgrades.',
    aliases: ['personal to business upgrades', 'upgrade conversion by source', 'shopper to business conversion'],
    improvementFocus: 'activation',
    preferredWidgetType: 'barChart',
    coverageStatus: 'needs_medusa_config',
    metricIds: ['personalToBusinessUpgrades'],
    dimensionId: 'signupSource',
    timeBucket: 'none',
    relativeRange: 'past_30_days',
    answerShape: 'barChart',
    filters: [],
    coverageNotes: [
      'Likely needs a join across lead, signup, and activation events or a purpose-built Medusa view for upgrade conversion.',
    ],
  },
  {
    id: 'weekly-icb-health-scorecard',
    category: 'business_health',
    persona: 'leadership',
    title: 'Weekly ICB health scorecard',
    prompt: 'Give me a weekly Instacart Business snapshot of GTV, orders, and average order value.',
    description: 'Canonical PM and sales scorecard for top-line marketplace health.',
    aliases: ['weekly business health', 'exec scorecard', 'gtv orders aov snapshot'],
    improvementFocus: 'health',
    preferredWidgetType: 'metric',
    coverageStatus: 'needs_medusa_config',
    metricIds: ['icbGtv', 'icbOrders', 'icbAvgOrderValue'],
    dimensionId: null,
    timeBucket: 'none',
    relativeRange: 'past_30_days',
    answerShape: 'metric',
    filters: [],
    coverageNotes: [
      'This is a top-priority stakeholder ask, but the workspace does not yet have verified Medusa aliases for the IC Business topline metrics.',
    ],
  },
  {
    id: 'top-retailers-by-icb-gtv',
    category: 'segment_breakdown',
    persona: 'sales',
    title: 'Top retailers by ICB GTV',
    prompt: 'Which retailers drove the most Instacart Business GTV in the last 30 days?',
    description: 'Retailer-level breakdown used in sales and PM readouts to understand partner contribution.',
    aliases: ['retailer gtv breakdown', 'top retailers', 'gtv by retailer'],
    improvementFocus: 'segmentation',
    preferredWidgetType: 'barChart',
    coverageStatus: 'needs_medusa_config',
    metricIds: ['icbGtv'],
    dimensionId: 'retailer',
    timeBucket: 'none',
    relativeRange: 'past_30_days',
    answerShape: 'barChart',
    filters: [],
    coverageNotes: [
      'Needs a verified retailer dimension in the IC Business Medusa model before it can be safely enabled.',
    ],
  },
  {
    id: 'aov-by-business-segment',
    category: 'segment_breakdown',
    persona: 'sales',
    title: 'Average order value by business segment',
    prompt: 'How does average order value differ across business segments this month?',
    description: 'Segment health question used during PM follow-up and sales reviews.',
    aliases: ['aov by segment', 'business segment aov', 'segment order value'],
    improvementFocus: 'segmentation',
    preferredWidgetType: 'barChart',
    coverageStatus: 'needs_medusa_config',
    metricIds: ['icbAvgOrderValue'],
    dimensionId: 'salesSegment',
    timeBucket: 'none',
    relativeRange: 'past_30_days',
    answerShape: 'barChart',
    filters: [],
    coverageNotes: [
      'Requires both an approved sales-segment dimension and a stable ICB AOV metric in Medusa.',
    ],
  },
  {
    id: 'invoicing-callout-effectiveness',
    category: 'invoicing',
    persona: 'pm',
    title: 'Invoicing callout effectiveness',
    prompt: 'Which invoicing callouts or surfaces are driving the strongest adoption lift?',
    description: 'PM-facing improvement question for feature messaging and invoicing adoption experiments.',
    aliases: ['invoice lift by surface', 'invoicing adoption drivers', 'callout effectiveness'],
    improvementFocus: 'invoicing',
    preferredWidgetType: 'table',
    coverageStatus: 'needs_medusa_config',
    metricIds: ['invoicingCalloutLift'],
    dimensionId: 'invoiceSurface',
    timeBucket: 'none',
    relativeRange: 'past_30_days',
    answerShape: 'table',
    filters: [],
    coverageNotes: [
      'Needs experiment or feature-surface attribution data plus a Medusa-safe derived metric for invoicing lift.',
    ],
  },
  {
    id: 'accounts-with-spend-drop',
    category: 'retention',
    persona: 'sales',
    title: 'Accounts with spend drop risk',
    prompt: 'Which business accounts have the sharpest spend drop over the last month?',
    description: 'Commercial watchlist question for proactive customer follow-up.',
    aliases: ['spend drop watchlist', 'at risk accounts', 'retention risk accounts'],
    improvementFocus: 'retention',
    preferredWidgetType: 'table',
    coverageStatus: 'needs_medusa_config',
    metricIds: ['icbSpendDropRisk'],
    dimensionId: 'businessId',
    timeBucket: 'none',
    relativeRange: 'past_30_days',
    answerShape: 'table',
    filters: [],
    coverageNotes: [
      'Likely needs account-level identifiers plus precomputed change metrics or a dedicated derived metric set.',
    ],
  },
  {
    id: 'partner-landing-page-performance',
    category: 'partner_reporting',
    persona: 'sales',
    title: 'Partner landing page performance',
    prompt: 'Which partner landing pages are driving the best business conversion this month?',
    description: 'Partner-reporting question for manual Mode workflows that need to become self-serve.',
    aliases: ['partner landing page report', 'landing page conversion', 'partner page performance'],
    improvementFocus: 'partner_reporting',
    preferredWidgetType: 'table',
    coverageStatus: 'needs_medusa_config',
    metricIds: ['landingPageConversion'],
    dimensionId: 'landingPage',
    timeBucket: 'none',
    relativeRange: 'past_30_days',
    answerShape: 'table',
    filters: [],
    coverageNotes: [
      'Needs stable partner attribution and landing-page metadata in Medusa before it can move out of manual reporting.',
    ],
  },
  {
    id: 'partner-sourced-business-signups',
    category: 'partner_reporting',
    persona: 'sales',
    title: 'Partner-sourced business signups',
    prompt: 'Which partners are sourcing the most new business signups this quarter?',
    description: 'Partner-channel reporting question used in recurring commercial updates.',
    aliases: ['partner signups', 'new businesses by partner', 'partner sourced growth'],
    improvementFocus: 'partner_reporting',
    preferredWidgetType: 'barChart',
    coverageStatus: 'needs_medusa_config',
    metricIds: ['partnerAttributedBusinesses'],
    dimensionId: 'partnerName',
    timeBucket: 'none',
    relativeRange: 'past_30_days',
    answerShape: 'barChart',
    filters: [],
    coverageNotes: [
      'Requires partner attribution plus a verified business signup metric in Medusa.',
    ],
  },
  {
    id: 'location-penetration-opportunities',
    category: 'retention',
    persona: 'sales',
    title: 'Location penetration opportunities',
    prompt: 'Which accounts have low location penetration relative to their total footprint?',
    description: 'Sales opportunity sizing question that combines internal order activity with external or CRM location counts.',
    aliases: ['location penetration', 'footprint opportunity', 'locations ordering gap'],
    improvementFocus: 'retention',
    preferredWidgetType: 'table',
    coverageStatus: 'blocked',
    metricIds: ['icbLocationPenetration'],
    dimensionId: 'accountOwner',
    timeBucket: 'none',
    relativeRange: 'past_30_days',
    answerShape: 'table',
    filters: [],
    coverageNotes: [
      'Blocked on non-Medusa enrichment because total location footprint does not come from the current Medusa path.',
    ],
  },
  {
    id: 'account-owner-book-health',
    category: 'business_health',
    persona: 'sales',
    title: 'Account owner book health',
    prompt: 'How is each account owner performing on GTV and retention risk across their book of business?',
    description: 'Sales-manager question that requires mapping business performance back to CRM ownership.',
    aliases: ['book of business health', 'owner performance', 'sales owner dashboard'],
    improvementFocus: 'health',
    preferredWidgetType: 'table',
    coverageStatus: 'blocked',
    metricIds: ['icbGtv', 'icbSpendDropRisk'],
    dimensionId: 'accountOwner',
    timeBucket: 'none',
    relativeRange: 'past_30_days',
    answerShape: 'table',
    filters: [],
    coverageNotes: [
      'Blocked until CRM or ownership metadata is brought into the same read path as Medusa business metrics.',
    ],
  },
] satisfies InsightQuestionDefinition[];

export const insightQuestionsById = Object.fromEntries(insightQuestionCatalog.map(question => [question.id, question])) as Record<
  InsightQuestionDefinition['id'],
  InsightQuestionDefinition
>;

export const readyInsightPrompts = insightQuestionCatalog
  .filter(question => question.coverageStatus === 'ready')
  .map(question => question.prompt);

export const defaultInsightPrompt = readyInsightPrompts[0] ?? 'How many business deliveries happened in the last 30 days?';

export const insightCoverageSummary = {
  totalQuestions: insightQuestionCatalog.length,
  readyQuestions: insightQuestionCatalog.filter(question => question.coverageStatus === 'ready').length,
  needsMedusaConfigQuestions: insightQuestionCatalog.filter(question => question.coverageStatus === 'needs_medusa_config').length,
  blockedQuestions: insightQuestionCatalog.filter(question => question.coverageStatus === 'blocked').length,
};
